In [1]:
import numpy as np

In [13]:
## With 1D array

In [3]:
data = np.array([10,20,30,40,50,1000]) #outlier in data

In [4]:
def min_max_normalization(data):
  min_val = np.min(data)
  max_val = np.max(data)
  normalized_data = (data - min_val) / (max_val - min_val)
  return normalized_data

In [6]:
def standardized_normalization(data):
  mean = np.mean(data)
  std = np.std(data)
  normalized_data = (data - mean)/std
  return normalized_data

In [7]:
## Applying min_max_normalization

In [8]:
data_norm1 = min_max_normalization(data)

In [9]:
data_norm1

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       1.        ])

In [10]:
## Applying standardized normalization

In [11]:
data_norm2 = standardized_normalization(data)

In [12]:
data_norm2

array([-0.50221883, -0.47457376, -0.44692869, -0.41928361, -0.39163854,
        2.23464343])

In [22]:
## With 2D array - here using the minimum and maximum across all the columns and then normalizing it

In [15]:
data2 = np.array([[1,2,3],[4,5,6],[7,8,100]])

In [16]:
data2

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8, 100]])

In [17]:
data2_norm1 = min_max_normalization(data2)

In [18]:
data2_norm1

array([[0.        , 0.01010101, 0.02020202],
       [0.03030303, 0.04040404, 0.05050505],
       [0.06060606, 0.07070707, 1.        ]])

In [19]:
data2_norm2 = standardized_normalization(data2)

In [20]:
data2_norm2

array([[-0.46895726, -0.43572407, -0.40249088],
       [-0.36925769, -0.3360245 , -0.3027913 ],
       [-0.26955811, -0.23632492,  2.82112874]])

In [23]:
## ML way - where we are supposed to take across individual column and then normalizing the values

In [24]:
data2

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8, 100]])

In [29]:
min_col = np.min(data2, axis=0) # each column independently

In [26]:
min_col

array([1, 2, 3])

In [30]:
max_col = np.max(data2, axis=0) # each column independently

In [28]:
max_col

array([  7,   8, 100])

In [31]:
min_max_norm = (data2 - min_col)/(max_col - min_col)

In [32]:
min_max_norm

array([[0.        , 0.        , 0.        ],
       [0.5       , 0.5       , 0.03092784],
       [1.        , 1.        , 1.        ]])

In [33]:
data2-min_col

array([[ 0,  0,  0],
       [ 3,  3,  3],
       [ 6,  6, 97]])

In [34]:
np_mean = np.mean(data2, axis=0)

In [35]:
np_mean

array([ 4.        ,  5.        , 36.33333333])

In [36]:
np_std = np.std(data2, axis =1 )

In [37]:
np_std

array([ 0.81649658,  0.81649658, 43.60682923])

In [38]:
data2_norm3 = (data2 - np_mean)/np_std

In [39]:
data2_norm3

array([[-3.67423461, -3.67423461, -0.76440626],
       [ 0.        ,  0.        , -0.6956097 ],
       [ 3.67423461,  3.67423461,  1.46001596]])